# .goreleaser.yaml
# See https://goreleaser.com for full documentation

before:
  hooks:
    - go mod tidy

builds:
  - id: default
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
    binary: '{{ .ProjectName }}_v{{ .Version }}'

archives:
  - id: default
    format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - id: default
    cmd: gpg
    artifacts: checksum
    args:
      - --batch
      - --pinentry-mode
      - loopback
      - --local-user
      - '{{ .Env.GPG_FINGERPRINT }}'
      - --passphrase
      - '{{ .Env.GPG_PASSPHRASE }}'
      - --output
      - '${signature}'
      - --detach-sign
      - '${artifact}'

release:
  draft: false

changelog:
  skip: true
