name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  test:
    if: "!startsWith(github.ref, 'refs/tags/')"  
    runs-on: ubuntu-latest
    services:
      ssh-test:
        image: rucciva/sshd:1.3.0
        ports:
          - "2222:22"
        env:
          SSH_ENABLE_ROOT: "true"
          SSH_ENABLE_PASSWORD_AUTH: "true"
          SSH_ROOT_AUTHORIZED_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDiH0y8fVWj472id/WIppOr3IiyTyu4LaHvEiuhJFa0SE1ns50WYq329DTaH0lN7lAp6+KoeBg+3hO2mcXwcGQp+JKQ5hfiIyCxQrlo6D1l3cnjkQL6Q0Y0RJ1jKJAsfQLwvNKMdyyXKXX9wbYJr1C/b+BorV/VZd3rvPoWum/JtgZlNirOjPKVv5YUlSyW7+DIvmzg7OC257RyA19gbej1of7KB+pPhriKdZe1HwOT+f5v03Aw8s5uKN7muX+wCbV3RafLSJFLpmyBj/nHXj6hAGVVhm+EN8MoNwvJ5zqjrX9c/B4UBc8FPc/9XL+bfKF0FK7/QGIdKfV7KG5ra94OcZxi9ILzNYIJy6Tb09i2xqn9S+8o/FUhi5oBcwjp0k93JVvkGVQF0JT7y4LXrNJkoam0UocttAzqqjdHvd364AMbbqey4/5aSnuacczdItL1kBXFqCk5VqmZ2Hw4Nq7HeAKyQrLF99mMIMo8vbom22LeybrBl+tfcq2VE6SAXjM= rucciva@R-MacbookPro
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Wait for SSH server
        run: |
          until nc -z localhost 2222; do sleep 1; done

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Test
        env:
          TEST_ACC_LINUX_PROVIDER_HOST: localhost
          TEST_ACC_LINUX_PROVIDER_PORT: 2222
        run: |
          make testacc
  
  release:
    if: startsWith(github.ref, 'refs/tags/')  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Release
        uses: goreleaser/goreleaser-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_FINGERPRINT: ${{ secrets.GPG_FINGERPRINT }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        with:
          version: '~> v2' 
          args: release --clean
